### ISSUE TITLE
Org joining link

### ISSUE THREAD

**Issue by himanshu007-creator** [Eaglion-Programmers/cheatsheets#1]
In case it is needed , we can make an invite page, where user enters his/her GitHub username and an invite to join this org i.e.
Eaglion-programmers will be sent.
Thoughts?
[reference](https://dscdaviet.herokuapp.com/)

**Comment by G-Sudarshan** [comment]
Yes, Awesome!! Please go ahead if you have any existing code as such or willing to make new one

**Comment by himanshu007-creator** [comment]
@G-Sudarshan  <a href="https://github.com/thundergolfer/automated-github-organization-invites#get-it-right-now">here</a> is the repo, you can simply click deploy to Heroku and replace the variables in accordance with our community.

**Comment by G-Sudarshan** [comment]
@himanshu007-creator I am not familiar with Ruby, I have forked the repo you mentioned and gave you admin access on that repo. Can you make the necessary changes for our organization?

**Comment by himanshu007-creator** [comment]
Hi @G-Sudarshan , this is not a coding job. We just need to login to organisations's heroku account, then  click ok the above link. We just need to fill the details. If heroku account is there the it's good, otherwise we can create a new account from organisations' GitHub account and make this happen

**Comment by G-Sudarshan** [comment]
@himanshu007-creator I have deployed it but it is giving some errors can you please check the .env file once? HEROKU URL is https://eaglion-programmers.herokuapp.com

**Comment by himanshu007-creator** [comment]
@G-Sudarshan  can you share Heroku credentials? or maybe we can discuss somewhere else?!

**Comment by G-Sudarshan** [comment]
@himanshu007-creator Can you please whatsapp me on 7030970237

**Comment by G-Sudarshan** [comment]
> Issue resolved by @himanshu007-creator
